"""Type stubs for the monomix._kernel PyO3 extension."""

from __future__ import annotations

__version__: str

class MonomixError(Exception): ...
class ParseError(MonomixError): ...
class EvalError(MonomixError): ...
class UnsupportedError(MonomixError): ...
class CrossSessionError(MonomixError): ...

class Expr:
    @property
    def kind(self) -> str: ...
    def is_same(self, other: Expr) -> bool: ...
    def __repr__(self) -> str: ...

class _SessionHandle:
    def __init__(self) -> None: ...
    def symbol(self, name: str) -> Expr: ...
    def integer(self, n: int) -> Expr: ...
    def rational(self, p: int, q: int) -> Expr: ...
    def parse(self, source: str) -> Expr: ...
