"""Type stubs for the monomix._kernel PyO3 extension."""

from __future__ import annotations

__version__: str

def simplify(e: Expr) -> Expr: ...

class MonomixError(Exception): ...
class ParseError(MonomixError): ...
class EvalError(MonomixError): ...
class UnsupportedError(MonomixError): ...
class CrossSessionError(MonomixError): ...

class Expr:
    @property
    def kind(self) -> str: ...
    def is_same(self, other: Expr) -> bool: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...

    # Arithmetic
    def __add__(self, other: Expr | int | float) -> Expr: ...
    def __radd__(self, other: Expr | int | float) -> Expr: ...
    def __sub__(self, other: Expr | int | float) -> Expr: ...
    def __rsub__(self, other: Expr | int | float) -> Expr: ...
    def __mul__(self, other: Expr | int | float) -> Expr: ...
    def __rmul__(self, other: Expr | int | float) -> Expr: ...
    def __truediv__(self, other: Expr | int | float) -> Expr: ...
    def __rtruediv__(self, other: Expr | int | float) -> Expr: ...
    def __pow__(self, other: Expr | int | float) -> Expr: ...
    def __rpow__(self, other: Expr | int | float) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def __pos__(self) -> Expr: ...

    # Comparison / equality
    def __eq__(self, other: object) -> Expr: ...  # type: ignore[override]
    def __ne__(self, other: object) -> Expr: ...  # type: ignore[override]
    def __lt__(self, other: Expr | int | float) -> Expr: ...
    def __le__(self, other: Expr | int | float) -> Expr: ...
    def __gt__(self, other: Expr | int | float) -> Expr: ...
    def __ge__(self, other: Expr | int | float) -> Expr: ...

    # Boolean
    def __and__(self, other: Expr) -> Expr: ...
    def __rand__(self, other: Expr) -> Expr: ...
    def __or__(self, other: Expr) -> Expr: ...
    def __ror__(self, other: Expr) -> Expr: ...
    def __invert__(self) -> Expr: ...

class _SessionHandle:
    def __init__(self) -> None: ...
    def symbol(self, name: str) -> Expr: ...
    def integer(self, n: int) -> Expr: ...
    def rational(self, p: int, q: int) -> Expr: ...
    def parse(self, source: str) -> Expr: ...
